# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  fetchgit,
  runCommand,
  bash,
}:

{
  name = "N-V-__8AANgeXQAuTDjDItrtITfVslPonFWB-h3Az2C0-2AM";
  path = runCommand "depot_tools-patch" { } ''
    cp -r ${
      fetchgit {
        url = "https://github.com/rust-skia/depot_tools";
        rev = "8efa575d754b8703d99b0f827528e45aeaa167aa";
        hash = "sha256-L6/leXNMZABDzfxMfzMFDmAhTJV631tNrSCwouMdaec=";
      }
    } $out
    patchShebangs $out
    chmod -R +w $out
    cat > "$out/ensure_bootstrap" << EOF
    #!${bash}/bin/bash
    exit 0
    EOF
    touch $out/.bootstrap-complete
  '';
}
