# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
  runCommand,
  bash,
}:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AADGOTAg2qy2JMjVSleelXVWZhf9UTIjkuioQsv9-";
    path = fetchgit {
      url = "https://github.com/google/boringssl";
      rev = "535cc391915c37912ff9b3edb0cff9b3c5c77db0";
      hash = "sha256-rSmfL4FC9QgIsQJWHwGlHuAR1ntHrK271A392FacQrs=";
    };
  }
  (import ./v8/deps.nix {
    inherit
      fetchgit
      runCommand
      bash
      ;
  })
  {
    name = "boringssl-0.1.0-VtJeWehMAAA4RNnwRnzEvKcS9rjsR1QVRw1uJrwXxmVK";
    path = fetchgit {
      url = "https://github.com/Syndica/boringssl-zig.git";
      rev = "c53df00d06b02b755ad88bbf4d1202ed9687b096";
      hash = "sha256-I6ST8fEQ35At/cRxjXJGxDiqZHhoJnW9n7GrhpO6RmE=";
    };
  }
  {
    name = "v8-0.0.0-xddH63lfBADJ7UE2zAJ8nJIBnxoSiimXSaX6Q_M_7DS3";
    path = fetchzip {
      url = "https://github.com/lightpanda-io/zig-v8-fork/archive/refs/tags/v0.2.8.tar.gz";
      hash = "sha256-Ck7n41Uye9AlSFwmvTyw2I+1IMrscS8v31iC3zHC7Uc=";
    };
  }
]
