# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  bash,
  fetchzip,
  fetchgit,
  fetchurl,
  lib,
  linkFarm,
  runCommand,
  stdenv,
}:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AADGOTAg2qy2JMjVSleelXVWZhf9UTIjkuioQsv9-";
    path = fetchgit {
      url = "https://github.com/google/boringssl";
      rev = "535cc391915c37912ff9b3edb0cff9b3c5c77db0";
      hash = "sha256-rSmfL4FC9QgIsQJWHwGlHuAR1ntHrK271A392FacQrs=";
    };
  }
  {
    name = "N-V-__8AANgeXQAuTDjDItrtITfVslPonFWB-h3Az2C0-2AM";
    path =
      let
        pin = lib.importJSON ./cipd_pin.json;

        cipd = fetchurl {
          url = "https://chrome-infra-packages.appspot.com/client?platform=${pin.${stdenv.system}.platform}&version=git_revision:${pin.git_revision}";
          hash = pin.${stdenv.system}.hash;
        };
      in
      runCommand "depot_tools-patch" { } ''
        cp -r ${
          fetchgit {
            url = "https://github.com/rust-skia/depot_tools";
            rev = "8efa575d754b8703d99b0f827528e45aeaa167aa";
            hash = "sha256-L6/leXNMZABDzfxMfzMFDmAhTJV631tNrSCwouMdaec=";
          }
        } $out
        patchShebangs $out
        chmod -R +w $out

        cat > "$out/ensure_bootstrap" << EOF
        #!${bash}/bin/bash
        exit 0
        EOF
        touch $out/.bootstrap-complete

        cp ${cipd} $out/.cipd_client
        chmod +x $out/.cipd_client

        cat > "$out/gclient" << EOF
        #!${bash}/bin/bash
        exit 0
        EOF
      '';
  }
  {
    name = "boringssl-0.1.0-VtJeWehMAAA4RNnwRnzEvKcS9rjsR1QVRw1uJrwXxmVK";
    path = fetchgit {
      url = "https://github.com/Syndica/boringssl-zig.git";
      rev = "c53df00d06b02b755ad88bbf4d1202ed9687b096";
      hash = "sha256-I6ST8fEQ35At/cRxjXJGxDiqZHhoJnW9n7GrhpO6RmE=";
    };
  }
  {
    name = "v8-0.0.0-xddH63lfBADJ7UE2zAJ8nJIBnxoSiimXSaX6Q_M_7DS3";
    path = fetchzip {
      url = "https://github.com/lightpanda-io/zig-v8-fork/archive/refs/tags/v0.2.8.tar.gz";
      hash = "sha256-Ck7n41Uye9AlSFwmvTyw2I+1IMrscS8v31iC3zHC7Uc=";
    };
  }
]
